load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "versionchecker",
    srcs = [
        "bazel.go",
        "bzlmod.go",
        "cargo.go",
        "crates.go",
        "golang.go",
        "gomod.go",
        "runner.go",
        "rust.go",
        "source.go",
    ],
    importpath = "github.com/uhvesta/monty-oxide/tools/versionchecker/internal",
    visibility = ["//tools/versionchecker/cmd:__pkg__"],
    deps = [
        "@com_github_bazelbuild_buildtools//build",
        "@com_github_burntsushi_toml//:toml",
    ],
)

go_test(
    name = "versionchecker_test",
    srcs = [
        "bzlmod_test.go",
        "cargo_test.go",
        "runner_test.go",
    ],
    embed = [":versionchecker"],
)
