load("@gazelle//:def.bzl", "gazelle")
load("@rules_shell//shell:sh_library.bzl", "sh_library")

exports_files([
    "Cargo.toml",
    "MODULE.bazel",
    ".clippy.toml",
    ".shellcheckrc",
    ".vale.ini",
])

# gazelle:prefix github.com/uhvesta/monty-oxide
gazelle(name = "gazelle")

alias(
    name = "format",
    actual = "//tools/format:format",
)

alias(
    name = "format.check",
    actual = "//tools/format:format.check",
)

alias(
    name = "check-deps",
    actual = "//tools/versionchecker/cmd:check-deps",
)

alias(
    name = "update-deps",
    actual = "//tools/versionchecker/cmd:update-deps",
)

filegroup(
    name = "markdown",
    srcs = glob(["*.md"]),
    tags = ["markdown"],
)

filegroup(
    name = "starlark",
    srcs = [
        "BUILD.bazel",
        "MODULE.bazel",
    ],
    tags = ["starlark"],
)

sh_library(
    name = "bootstrap_bazelisk",
    srcs = ["//tools:scripts/bootstrap/bazelisk.sh"],
)

sh_library(
    name = "bootstrap_devtools",
    srcs = ["//tools:scripts/bootstrap/devtools.sh"],
)
