load("@rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_binary(
    name = "versionchecker",
    args = [
        "--go-runfile",
        "$(rlocationpath @go_sdk//:bin/go)",
    ],
    data = [
        "@go_sdk//:bin/go",
    ],
    embed = [":versionchecker_lib"],
    visibility = ["//visibility:public"],
)

go_binary(
    name = "check-deps",
    args = [
        "--go-runfile",
        "$(rlocationpath @go_sdk//:bin/go)",
        "check",
    ],
    data = [
        "@go_sdk//:bin/go",
    ],
    embed = [":versionchecker_lib"],
    visibility = ["//visibility:public"],
)

go_binary(
    name = "update-deps",
    args = [
        "--go-runfile",
        "$(rlocationpath @go_sdk//:bin/go)",
        "fix",
    ],
    data = [
        "@go_sdk//:bin/go",
    ],
    embed = [":versionchecker_lib"],
    visibility = ["//visibility:public"],
)

go_library(
    name = "versionchecker_lib",
    srcs = [
        "command.go",
        "main.go",
    ],
    importpath = "github.com/uhvesta/monty-oxide/tools/versionchecker/cmd",
    visibility = ["//visibility:private"],
    deps = [
        "//tools/versionchecker/internal:versionchecker",
        "@com_github_spf13_cobra//:cobra",
    ],
)

go_test(
    name = "versionchecker_test",
    srcs = ["command_test.go"],
    embed = [":versionchecker_lib"],
    deps = ["//tools/versionchecker/internal:versionchecker"],
)
