load("@aspect_rules_lint//format:defs.bzl", "format_multirun", "format_test")
load("@rust_metadata//:edition.bzl", "RUST_EDITION")

filegroup(
    name = "starlark",
    srcs = ["BUILD.bazel"],
    tags = ["starlark"],
)

format_multirun(
    name = "format",
    go = "@aspect_rules_lint//format:gofumpt",
    markdown = "@rumdl//:rumdl",
    markdown_check_args = [
        "fmt",
        "--check",
    ],
    markdown_fix_args = ["fmt"],
    rust = "@rules_rust//tools/upstream_wrapper:rustfmt",
    rust_check_args = [
        "--edition",
        RUST_EDITION,
        "--check",
    ],
    rust_fix_args = [
        "--edition",
        RUST_EDITION,
    ],
    shell = "@shfmt//:shfmt",
    shell_check_args = [
        "--diff",
        "--apply-ignore",
        "-i",
        "2",
        "-ci",
    ],
    shell_fix_args = [
        "-w",
        "--apply-ignore",
        "-i",
        "2",
        "-ci",
    ],
    starlark = "@buildifier//:buildifier",
    visibility = ["//:__pkg__"],
)

# Not hermetic but it's fine
format_test(
    name = "format_test",
    size = "small",
    fix_target = ":format",
    go = "@aspect_rules_lint//format:gofumpt",
    markdown = "@rumdl//:rumdl",
    markdown_check_args = [
        "fmt",
        "--check",
    ],
    no_sandbox = True,
    rust = "@rules_rust//tools/upstream_wrapper:rustfmt",
    rust_check_args = [
        "--edition",
        RUST_EDITION,
        "--check",
    ],
    shell = "@shfmt//:shfmt",
    shell_check_args = [
        "--diff",
        "--apply-ignore",
        "-i",
        "2",
        "-ci",
    ],
    starlark = "@buildifier//:buildifier",
    tags = ["local"],
    workspace = "//:MODULE.bazel",
)
