load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "versionchecker",
    srcs = [
        "bazel.go",
        "bzlmod.go",
        "golang.go",
        "runner.go",
        "rust.go",
        "source.go",
    ],
    importpath = "github.com/uhvesta/monty-oxide/tools/internal/versionchecker",
    visibility = ["//tools:__subpackages__"],
)

go_test(
    name = "versionchecker_test",
    srcs = ["runner_test.go"],
    embed = [":versionchecker"],
)
